---
title: "Research"
listing:
  id: pubs-listing
  contents: publications
  sort: "date desc"
  type: grid
  page-size: 3
  fields: [title, subtitle, author, date, description, image]
---

Explore some of my recent publications here. A comprehensive list of my scholarly work is available below.

## Featured

:::{#pubs-listing}
:::

## Peer-reviewed publications

#### 2025

**Galligan, B. P.**, McManus, M. C., & Balouskus, R. G. Drivers of Winter Flounder subpopulation catch rates in a fisheries-independent fixed gear survey. *Transactions of the American Fisheries Society*, *154*(4), 456--468. [doi](https://doi.org/10.1093/tafafs/vnaf022) [pdf](data-files/galliganetal2025.pdf) [data](https://doi.org/10.5281/zenodo.14224683)

#### 2024

**Galligan, B. P.**, Saldivar, F. C., & Maina, G. W. Human dignity is on the line: Small-scale fisheries, blue growth, and human rights in Lamu, Kenya. In J. Nakamura, R. Chuenpagdee, & S. Jentoft (Eds.), *Implementation of the Small-Scale Fisheries Guidelines: A legal and policy scan* (pp. 99--120). Springer. [doi](https://doi.org/10.1007/978-3-031-56716-2_6) [request pdf](mailto:bgalligan@jesuits.org)

**Galligan, B. P.**, & McClanahan, T. R. Tropical fishery nutrient production depends on biomass-based management. *iScience*, *27*(4), 109420. [doi](https://doi.org/10.1016/j.isci.2024.109420) [pdf](data-files/galliganmcclanahan2024b.pdf) [code](https://doi.org/10.5281/zenodo.10149658)

**Galligan, B. P.**, & McClanahan, T. R. Nutrition contributions of coral reef fisheries not enhanced by capture of small fish. *Ocean and Coastal Management*, *249*, 107011. [doi](https://doi.org/10.1016/j.ocecoaman.2023.107011) [pdf](data-files/galliganmcclanahan2024.pdf)

#### 2022

**Galligan, B. P.**, McClanahan, T. R., & Humphries, A. T. Nutrient capture and sustainable yield maximized by a gear modification in artisanal fishing traps. *Environmental Research Letters*, *17*(12), 124035. [doi](https://doi.org/10.1088/1748-9326/aca77e) [pdf](data-files/galliganetal2022b.pdf) [data](https://doi.org/10.5281/zenodo.7256316)

**Galligan, B. P.** Re-theorising the genocide–ecocide nexus: Raphael Lemkin and ecocide in the Amazon. *The International Journal of Human Rights*, *26*(6), 1004–1031. [doi](https://doi.org/10.1080/13642987.2021.1994402) [pdf](data-files/galligan2022.pdf)

**Galligan, B. P.**, Stuart, Y. E., McManus, M. C., & Stoffel, H. E. Hypoxia-induced predation refuge for northern quahogs (*Mercenaria mercenaria*) in a temperate estuary. *Estuarine, Coastal and Shelf Science*, *265*, 107732. [doi](https://doi.org/10.1016/j.ecss.2021.107732) [pdf](data-files/galliganetal2022.pdf) [data](https://doi.org/10.5061/dryad.fn2z34tw5)

#### 2021

**Galligan, B. P.** Fisheries extractivism and the right to subsistence: Conflicting governance models and the legal structures that enact them. *Marine Policy*, *133*, 104729. [doi](https://doi.org/10.1016/j.marpol.2021.104729) [pdf](data-files/galligan2021.pdf)

## Selected additional publications

#### 2023

Darío Palacio, R. D., Abarca, M., Armenteras, D., Balza, U., Dollar, L. J., Froese, G. Z. L., **Galligan, B. P.**, Giordano A. J., Gula, J., Jacobson, A. P., Jędrzejewski, W., Khorozyan, I., Mastretta-Yanes, A., Moreno, J. S., Mudumba, T., Nana, E. D., Naveda-Rodríguez, A., Negret, P. J., Ortuño Crespo, G., Serrano, F. C., Serrano-Villavicencio, J. E., Gopi Sundar, K. S., Thomas, E., Villar, D. A., & Hughes, A. C. The global influence of the IUCN Red List can hinder species conservation efforts. *Authorea*. [doi](https://doi.org/10.22541/au.169945445.50394320/v1) [pdf](data-files/dariopalacio2023.pdf)

Zepeda, C. S., & **Galligan, B. P.** *Integral ecology in research practice: Methodological insights for transformative change* (Briefing Note No. 6). Laudato Si' Research Institute, Campion Hall, University of Oxford. [link](https://lsri.campion.ox.ac.uk/publications/integral-ecology-research-practice-methodological-insights-transformative-change) [pdf](data-files/zepeda2023.pdf)

#### 2022

**Galligan, B. P.**, Werth, E., Phiri, M., & Orthi, O. *One complex crisis: Case studies of environmental and social (in)justice in Africa*. Jesuit Justice and Ecology Network Africa. [link](https://www.jenaafrica.org/wp-content/uploads/2022/07/GalliganEtAl_OneCrisis_JENA_6.15.22.pdf) [pdf](data-files/galliganetal2022c.pdf)

Athman, M., and **B. P. Galligan**. Lamu Old Town faces mounting pressures under climate change and large-scale infrastructure development. In S. Doempke, N. Bolomey, R. M. Ebrahimi Saba, M. F. Oliveira, J. P. de Oliveira Costa, and S. Wagh, (Eds.), *World Heritage Watch Report* (pp. 209--212). [link](https://world-heritage-watch.org/content/wp-content/uploads/2022/11/2022-Report-WHW-final.pdf#page=211) [pdf](data-files/athmangalligan2022.pdf)

#### 2021

**Galligan, B. P.**, & Kinney, S. Providing access or taking sides? Blue growth, small-scale fisheries, and the case of Lamu, Kenya. *Promotio Iustitiae*, *132*(2), 87–94. [link](https://www.sjesjesuits.global/media/2021/12/PJ_132_ENG.pdf#page=87) [pdf](data-files/galligankinney2021.pdf)


